Fixed back script options

diff --git a/build_bin/kairos_python_dependencies b/build_bin/kairos_python_dependencies
--- a/build_bin/kairos_python_dependencies
+++ b/build_bin/kairos_python_dependencies
@@ -1,5 +1,8 @@
 #!/bin/bash -e
 
+# pipefail shell option means we still bail on error
+set -o pipefail
+
 . $(which kairos_env_init)
 script_init # install error hooks
 
@@ -9,7 +12,6 @@ if [ -f requirements.txt ]; then
   echo " See logs/dependencies-install.log in artifacts for detailed output"
   mkdir -p dist
   # pipe to cat to suppress the status bars.
-  # pipefail shell option means we still bail on error
   pip install --log logs/dependencies-install.log -r requirements.txt | cat
 else
   echo "WARNING: no requirements file found. (this is likely a bug)"
